//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public string 交易序號 { get; set; }
        public string 醫療機構名稱 { get; set; }
        public string 就醫帳號 { get; set; }
        public string 手機 { get; set; }
        public string 姓名 { get; set; }
        public string 身分證號碼 { get; set; }
        public string 出生年 { get; set; }
        public string 科別 { get; set; }
        public string 系統別 { get; set; }
        public string 時段 { get; set; }
        public string 金額 { get; set; }
        public string 繳費日期 { get; set; }
        public string 繳費方式 { get; set; }
        public string 信用卡卡號 { get; set; }
        public string 信用卡訂單編號 { get; set; }
        public string 信用卡授權碼 { get; set; }
    }
}
